<a href="https://colab.research.google.com/github/Qan123/Machine-Learning/blob/main/Encoding_Catagorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('disease.csv')
df.sample(n = 5, random_state=99)

gender         city   age      bp cough disease
14    Male  Shaikhupura  51.0     low  Mild      No
34    Male      Karachi  74.0     low  Mild     Yes
30    Male    Islamabad  15.0     low  Mild     Yes
78    Male  Shaikhupura  11.0     low  Mild     Yes
16  Female       Lahore  69.0  normal  Mild     Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gender   100 non-null    object 
 1   city     100 non-null    object 
 2   age      87 non-null     float64
 3   bp       100 non-null    object 
 4   cough    100 non-null    object 
 5   disease  100 non-null    object 
dtypes: float64(1), object(5)
memory usage: 4.8+ KB


In [6]:
df.nunique()

gender      2
city        4
age        54
bp          3
cough       3
disease     2
dtype: int64

In [7]:
df.shape

(100, 6)

In [8]:
df.city.value_counts()

Lahore         32
Shaikhupura    30
Islamabad      22
Karachi        16
Name: city, dtype: int64

In [9]:
df.bp.value_counts()

normal    47
low       28
high      25
Name: bp, dtype: int64

In [10]:
df.gender.value_counts()

Female    59
Male      41
Name: gender, dtype: int64

## Label encoder

In [11]:
df.head()

gender       city   age      bp     cough disease
0    Male     Lahore  60.0     low  Moderate     Yes
1    Male  Islamabad  27.0     low      Mild      No
2    Male  Islamabad   NaN  normal    Strong      No
3  Female     Lahore  31.0    high  Moderate     Yes
4  Female    Karachi  65.0    high      Mild      No

In [12]:
y = df.iloc[:, -1]
y

0     Yes
1      No
2      No
3     Yes
4      No
     ... 
95     No
96    Yes
97     No
98     No
99    Yes
Name: disease, Length: 100, dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)
label_disease = le.transform(y)
label_disease

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [14]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [15]:
label_disease.shape

(100,)


## Ordinal Encoder

In [16]:
y = df.iloc[:, 3:5]
y

bp     cough
0      low  Moderate
1      low      Mild
2   normal    Strong
3     high  Moderate
4     high      Mild
..     ...       ...
95  normal      Mild
96    high    Strong
97  normal      Mild
98     low  Moderate
99     low    Strong

[100 rows x 2 columns]

In [17]:
from sklearn.preprocessing import OrdinalEncoder
oe  = OrdinalEncoder(categories=[['low', 'normal', 'high'], ['Mild', 'Moderate', 'Strong']], dtype = np.int8)
oe.fit(y)
bp_cough_arr = oe.transform(y)
bp_cough_arr , bp_cough_arr.shape

(array([[0, 1],
        [0, 0],
        [1, 2],
        [2, 1],
        [2, 0],
        [2, 0],
        [1, 2],
        [1, 1],
        [2, 2],
        [0, 0],
        [0, 0],
        [2, 1],
        [1, 2],
        [0, 0],
        [0, 0],
        [1, 2],
        [1, 0],
        [0, 1],
        [2, 0],
        [2, 2],
        [0, 2],
        [2, 1],
        [1, 2],
        [1, 0],
        [1, 1],
        [1, 0],
        [2, 1],
        [1, 2],
        [1, 0],
        [2, 1],
        [0, 0],
        [1, 0],
        [2, 2],
        [1, 1],
        [0, 0],
        [1, 2],
        [1, 0],
        [1, 1],
        [2, 0],
        [1, 1],
        [1, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [1, 2],
        [1, 0],
        [1, 1],
        [1, 0],
        [0, 1],
        [0, 0],
        [1, 0],
        [2, 1],
        [2, 2],
        [2, 0],
        [1, 0],
        [1, 0],
        [2, 2],
        [0, 2],
        [0, 2],
        [2, 0],
        [1, 2],
        [0, 1],
        

In [18]:
oe.categories_

[array(['low', 'normal', 'high'], dtype=object),
 array(['Mild', 'Moderate', 'Strong'], dtype=object)]

## one hot encoding

In [19]:
df_gender_city = df.iloc[:, 0: 2]
df_gender_city

gender         city
0     Male       Lahore
1     Male    Islamabad
2     Male    Islamabad
3   Female       Lahore
4   Female      Karachi
..     ...          ...
95  Female  Shaikhupura
96  Female       Lahore
97  Female  Shaikhupura
98  Female      Karachi
99  Female       Lahore

[100 rows x 2 columns]

In [20]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output = False, dtype = np.int32)
ohe.fit(df_gender_city)
arr_gender_city = ohe.transform(df_gender_city)
arr_gender_city, arr_gender_city.shape

(array([[1, 0, 1, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 1],
        [1, 0, 0, 1],
        [1, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 0, 0, 1],
        [1, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 0, 0],
        [0, 0, 1, 0],
        [1, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 0],
        [1, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 1, 0],
        [0, 0, 0, 0],
        [0, 0, 1, 0],
        [1, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 0, 1, 0],
        [0, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 0],
        [1, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [1

In [21]:
ohe.categories_

[array(['Female', 'Male'], dtype=object),
 array(['Islamabad', 'Karachi', 'Lahore', 'Shaikhupura'], dtype=object)]

## Perform train-test split and then perform transformation

In [22]:
df.head()

gender       city   age      bp     cough disease
0    Male     Lahore  60.0     low  Moderate     Yes
1    Male  Islamabad  27.0     low      Mild      No
2    Male  Islamabad   NaN  normal    Strong      No
3  Female     Lahore  31.0    high  Moderate     Yes
4  Female    Karachi  65.0    high      Mild      No

In [23]:
x = df.drop('disease', axis = 1)
x

gender         city   age      bp     cough
0     Male       Lahore  60.0     low  Moderate
1     Male    Islamabad  27.0     low      Mild
2     Male    Islamabad   NaN  normal    Strong
3   Female       Lahore  31.0    high  Moderate
4   Female      Karachi  65.0    high      Mild
..     ...          ...   ...     ...       ...
95  Female  Shaikhupura   NaN  normal      Mild
96  Female       Lahore  51.0    high    Strong
97  Female  Shaikhupura  20.0  normal      Mild
98  Female      Karachi   5.0     low  Moderate
99  Female       Lahore  10.0     low    Strong

[100 rows x 5 columns]

In [24]:
y = df['disease']
y

0     Yes
1      No
2      No
3     Yes
4      No
     ... 
95     No
96    Yes
97     No
98     No
99    Yes
Name: disease, Length: 100, dtype: object

In [25]:
from pandas.core.common import random_state
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size =0.2, random_state=99)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((80, 5), (20, 5), (80,), (20,))

In [26]:
X_train.head()


gender         city   age      bp cough
97  Female  Shaikhupura  20.0  normal  Mild
4   Female      Karachi  65.0    high  Mild
45    Male  Shaikhupura  72.0  normal  Mild
54  Female      Karachi  60.0  normal  Mild
25    Male      Karachi   NaN  normal  Mild

In [27]:
X_test.head()

gender         city   age      bp cough
14    Male  Shaikhupura  51.0     low  Mild
34    Male      Karachi  74.0     low  Mild
30    Male    Islamabad  15.0     low  Mild
78    Male  Shaikhupura  11.0     low  Mild
16  Female       Lahore  69.0  normal  Mild

In [28]:
Y_train.head()

97     No
4      No
45     No
54    Yes
25     No
Name: disease, dtype: object

In [29]:
Y_test.head()

14     No
34    Yes
30    Yes
78    Yes
16    Yes
Name: disease, dtype: object

## One hot encoding on gender and city

In [30]:
one = OneHotEncoder(drop='first', sparse_output = False, dtype = np.int32)
one.fit(X_train[['gender', 'city']])
gender_city_train = one.transform(X_train[['gender', 'city']])
gender_city_test  = one.transform(X_test[['gender', 'city']])
gender_city_train.shape, gender_city_test.shape


((80, 4), (20, 4))

## Applying Ordinal Encoder to bp and cough column

In [31]:
oe  = OrdinalEncoder(categories=[['low', 'normal', 'high'], ['Mild', 'Moderate', 'Strong']], dtype = np.int8)
oe.fit(X_train[['bp', 'cough']])
X_train_bp_cough_arr = oe.transform(X_train[['bp', 'cough']])
X_test_bp_cough_arr = oe.transform(X_test[['bp', 'cough']])
X_train_bp_cough_arr.shape, X_test_bp_cough_arr.shape

((80, 2), (20, 2))

## Applying Label Encoder on disease column

In [32]:
le = LabelEncoder()
le.fit(Y_train)
y_train = le.transform(Y_train)
y_test = le.transform(Y_test)
y_train.shape, y_test.shape

((80,), (20,))

In [33]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0])

## Apply simple imputer to Age column

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gender   100 non-null    object 
 1   city     100 non-null    object 
 2   age      87 non-null     float64
 3   bp       100 non-null    object 
 4   cough    100 non-null    object 
 5   disease  100 non-null    object 
dtypes: float64(1), object(5)
memory usage: 4.8+ KB


In [35]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values = np.nan, strategy = 'mean')

si.fit(X_train[['age']])
x_train_age = si.transform(X_train[['age']])
x_test_age = si.transform(X_test[['age']])
x_train_age.shape, x_test_age.shape

((80, 1), (20, 1))

## Combine

In [36]:
X_trained_transformed = np.concatenate((X_train_bp_cough_arr, x_train_age,  gender_city_train ), axis = 1)
X_trained_transformed.shape

(80, 7)

In [37]:
X_test_transformed = np.concatenate((X_test_bp_cough_arr, x_test_age,  gender_city_test ), axis = 1)
X_test_transformed.shape

(20, 7)

In [38]:
X_trained_transformed_df = pd.DataFrame(X_trained_transformed,
                                        columns=['gender', 'city1', 'city2', 'city3', 'age', 'bp', 'cough'])
X_trained_transformed_df.shape

(80, 7)

In [39]:
X_train.head()

gender         city   age      bp cough
97  Female  Shaikhupura  20.0  normal  Mild
4   Female      Karachi  65.0    high  Mild
45    Male  Shaikhupura  72.0  normal  Mild
54  Female      Karachi  60.0  normal  Mild
25    Male      Karachi   NaN  normal  Mild

In [40]:
X_trained_transformed_df.head()

gender  city1      city2  city3  age   bp  cough
0     1.0    0.0  20.000000    0.0  0.0  0.0    1.0
1     2.0    0.0  65.000000    0.0  1.0  0.0    0.0
2     1.0    0.0  72.000000    1.0  0.0  0.0    1.0
3     1.0    0.0  60.000000    0.0  1.0  0.0    0.0
4     1.0    0.0  44.617647    1.0  1.0  0.0    0.0

In [41]:
X_test_transformed_df = pd.DataFrame(X_test_transformed,
                                        columns=['gender', 'city1', 'city2', 'city3', 'age', 'bp', 'cough'])
X_test_transformed_df.shape

(20, 7)

In [42]:
X_test.head()

gender         city   age      bp cough
14    Male  Shaikhupura  51.0     low  Mild
34    Male      Karachi  74.0     low  Mild
30    Male    Islamabad  15.0     low  Mild
78    Male  Shaikhupura  11.0     low  Mild
16  Female       Lahore  69.0  normal  Mild

In [43]:
X_test_transformed_df.head()

gender  city1  city2  city3  age   bp  cough
0     0.0    0.0   51.0    1.0  0.0  0.0    1.0
1     0.0    0.0   74.0    1.0  1.0  0.0    0.0
2     0.0    0.0   15.0    1.0  0.0  0.0    0.0
3     0.0    0.0   11.0    1.0  0.0  0.0    1.0
4     1.0    0.0   69.0    0.0  0.0  1.0    0.0

## Using Column transformer to Impute

In [45]:
ohe = OneHotEncoder(drop = 'first', sparse= False, dtype = np.int32)

oe = OrdinalEncoder(categories = [['low', 'normal', 'high'], ['Mild', 'Moderate', 'Strong']], dtype = np.int8)

si = SimpleImputer(missing_values = np.nan, strategy='mean')


In [46]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers= [
    ('tfm1' , ohe, ['gender', 'city']),
    ('tfm2', oe , ['bp', 'cough']),
    ('tfm3', si, ['age'])
    ], remainder='passthrough')

In [48]:
transformer.fit(X_train)

X_trained_transformed1 = transformer.transform(X_train)
X_test_transformed1 = transformer.transform(X_test)

X_trained_transformed_df1 = pd.DataFrame(X_trained_transformed1, columns=['gender', 'city1', 'city2', 'city3', 'age', 'bp', 'cough'])
X_trained_transformed_df1

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


gender  city1  city2  city3  age   bp      cough
0      0.0    0.0    0.0    1.0  1.0  0.0  20.000000
1      0.0    1.0    0.0    0.0  2.0  0.0  65.000000
2      1.0    0.0    0.0    1.0  1.0  0.0  72.000000
3      0.0    1.0    0.0    0.0  1.0  0.0  60.000000
4      1.0    1.0    0.0    0.0  1.0  0.0  44.617647
..     ...    ...    ...    ...  ...  ...        ...
75     1.0    0.0    1.0    0.0  1.0  2.0  34.000000
76     0.0    0.0    0.0    0.0  1.0  0.0  49.000000
77     0.0    0.0    0.0    1.0  0.0  2.0  44.617647
78     0.0    0.0    0.0    1.0  1.0  2.0  44.617647
79     1.0    0.0    0.0    0.0  0.0  0.0  27.000000

[80 rows x 7 columns]